// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using atm_api_net_core;

namespace atm_api_net_core.Migrations
{
    [DbContext(typeof(AtmContext))]
    [Migration("20210226024149_valoresPorDefecto")]
    partial class valoresPorDefecto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("atm_api_net_core.Tarjeta.Entities.TarjetaEntity", b =>
                {
                    b.Property<int>("IdTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTarjeta")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Bloqueado");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Creacion")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Intentos")
                        .HasColumnType("int")
                        .HasColumnName("Intentos");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("0")
                        .HasColumnName("Numero");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Pin");

                    b.HasKey("IdTarjeta");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Tarjeta");

                    b.HasData(
                        new
                        {
                            IdTarjeta = 1,
                            Bloqueado = false,
                            FechaActualizacion = new DateTime(2021, 2, 25, 23, 41, 49, 9, DateTimeKind.Local).AddTicks(5140),
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Intentos = 0,
                            Numero = "1111111111111111",
                            Pin = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
